services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./src:/app:rw 
      - ./data/database.db:/app/database.db:rw
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    tty: true

  job:
    build:
      context: .
      dockerfile: Dockerfile.job
    volumes:
      - ./src:/app:rw 
      - ./data/database.db:/app/database.db:ro
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    tty: true
