services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - ./src:/app:rw 
      - ./data/database.db:/app/database.db:rw
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    command: ["python3", "main.py"]
    tty: true

  job:
    restart: always
    build:
      context: .
    volumes:
      - ./src:/app:rw 
      - ./data/database.db:/app/database.db:ro
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    command: ["python3", "job.py"]
    tty: true
