services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - ./data:/app/data:rw
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    command: ["python3", "main.py"]
    tty: true

  job:
    restart: always
    build:
      context: .
    volumes:
      - ./data:/app/data:ro
    env_file:
      - .env
    depends_on:
      - "app"
    environment:
      - TZ=Asia/Tokyo
    command: ["python3", "job.py"]
    tty: true
